// カメラマスターデータ - 人気のカメラ機種
export const cameraMastersData = [
  // Canon
  {
    manufacturer: "Canon",
    model: "EOS R5",
    releaseYear: 2020,
    sensor: "Full-frame",
    mount: "RF",
  },
  {
    manufacturer: "Canon",
    model: "EOS R6 Mark II",
    releaseYear: 2022,
    sensor: "Full-frame",
    mount: "RF",
  },
  {
    manufacturer: "Canon",
    model: "EOS R7",
    releaseYear: 2022,
    sensor: "APS-C",
    mount: "RF",
  },
  {
    manufacturer: "Canon",
    model: "EOS R8",
    releaseYear: 2023,
    sensor: "Full-frame",
    mount: "RF",
  },
  {
    manufacturer: "Canon",
    model: "EOS R10",
    releaseYear: 2022,
    sensor: "APS-C",
    mount: "RF",
  },
  {
    manufacturer: "Canon",
    model: "EOS 5D Mark IV",
    releaseYear: 2016,
    sensor: "Full-frame",
    mount: "EF",
  },

  // Sony
  {
    manufacturer: "Sony",
    model: "α7 IV",
    releaseYear: 2021,
    sensor: "Full-frame",
    mount: "E",
  },
  {
    manufacturer: "Sony",
    model: "α7 III",
    releaseYear: 2018,
    sensor: "Full-frame",
    mount: "E",
  },
  {
    manufacturer: "Sony",
    model: "α7R V",
    releaseYear: 2022,
    sensor: "Full-frame",
    mount: "E",
  },
  {
    manufacturer: "Sony",
    model: "α7R IV",
    releaseYear: 2019,
    sensor: "Full-frame",
    mount: "E",
  },
  {
    manufacturer: "Sony",
    model: "α6700",
    releaseYear: 2023,
    sensor: "APS-C",
    mount: "E",
  },
  {
    manufacturer: "Sony",
    model: "α6600",
    releaseYear: 2019,
    sensor: "APS-C",
    mount: "E",
  },
  {
    manufacturer: "Sony",
    model: "α1",
    releaseYear: 2021,
    sensor: "Full-frame",
    mount: "E",
  },

  // Nikon
  {
    manufacturer: "Nikon",
    model: "Z9",
    releaseYear: 2021,
    sensor: "Full-frame",
    mount: "Z",
  },
  {
    manufacturer: "Nikon",
    model: "Z8",
    releaseYear: 2023,
    sensor: "Full-frame",
    mount: "Z",
  },
  {
    manufacturer: "Nikon",
    model: "Z6 III",
    releaseYear: 2024,
    sensor: "Full-frame",
    mount: "Z",
  },
  {
    manufacturer: "Nikon",
    model: "Z6 II",
    releaseYear: 2020,
    sensor: "Full-frame",
    mount: "Z",
  },
  {
    manufacturer: "Nikon",
    model: "Z7 II",
    releaseYear: 2020,
    sensor: "Full-frame",
    mount: "Z",
  },
  {
    manufacturer: "Nikon",
    model: "Z50",
    releaseYear: 2019,
    sensor: "APS-C",
    mount: "Z",
  },
  {
    manufacturer: "Nikon",
    model: "Z fc",
    releaseYear: 2021,
    sensor: "APS-C",
    mount: "Z",
  },

  // Fujifilm
  {
    manufacturer: "Fujifilm",
    model: "X-T5",
    releaseYear: 2022,
    sensor: "APS-C",
    mount: "X",
  },
  {
    manufacturer: "Fujifilm",
    model: "X-T4",
    releaseYear: 2020,
    sensor: "APS-C",
    mount: "X",
  },
  {
    manufacturer: "Fujifilm",
    model: "X-H2S",
    releaseYear: 2022,
    sensor: "APS-C",
    mount: "X",
  },
  {
    manufacturer: "Fujifilm",
    model: "X-H2",
    releaseYear: 2022,
    sensor: "APS-C",
    mount: "X",
  },
  {
    manufacturer: "Fujifilm",
    model: "X-S20",
    releaseYear: 2023,
    sensor: "APS-C",
    mount: "X",
  },
  {
    manufacturer: "Fujifilm",
    model: "X-E4",
    releaseYear: 2021,
    sensor: "APS-C",
    mount: "X",
  },
];

// レンズマスターデータ - 人気のレンズ
export const lensMastersData = [
  // Canon RF
  {
    manufacturer: "Canon",
    model: "RF 24-70mm F2.8 L IS USM",
    focalLength: "24-70mm",
    aperture: "f/2.8",
    mount: "RF",
    releaseYear: 2018,
  },
  {
    manufacturer: "Canon",
    model: "RF 70-200mm F2.8 L IS USM",
    focalLength: "70-200mm",
    aperture: "f/2.8",
    mount: "RF",
    releaseYear: 2019,
  },
  {
    manufacturer: "Canon",
    model: "RF 50mm F1.8 STM",
    focalLength: "50mm",
    aperture: "f/1.8",
    mount: "RF",
    releaseYear: 2020,
  },
  {
    manufacturer: "Canon",
    model: "RF 85mm F1.2 L USM",
    focalLength: "85mm",
    aperture: "f/1.2",
    mount: "RF",
    releaseYear: 2019,
  },
  {
    manufacturer: "Canon",
    model: "RF 15-35mm F2.8 L IS USM",
    focalLength: "15-35mm",
    aperture: "f/2.8",
    mount: "RF",
    releaseYear: 2019,
  },

  // Sony E
  {
    manufacturer: "Sony",
    model: "FE 24-70mm F2.8 GM II",
    focalLength: "24-70mm",
    aperture: "f/2.8",
    mount: "E",
    releaseYear: 2022,
  },
  {
    manufacturer: "Sony",
    model: "FE 70-200mm F2.8 GM OSS II",
    focalLength: "70-200mm",
    aperture: "f/2.8",
    mount: "E",
    releaseYear: 2021,
  },
  {
    manufacturer: "Sony",
    model: "FE 50mm F1.8",
    focalLength: "50mm",
    aperture: "f/1.8",
    mount: "E",
    releaseYear: 2016,
  },
  {
    manufacturer: "Sony",
    model: "FE 85mm F1.4 GM",
    focalLength: "85mm",
    aperture: "f/1.4",
    mount: "E",
    releaseYear: 2016,
  },
  {
    manufacturer: "Sony",
    model: "FE 16-35mm F2.8 GM",
    focalLength: "16-35mm",
    aperture: "f/2.8",
    mount: "E",
    releaseYear: 2017,
  },

  // Nikon Z
  {
    manufacturer: "Nikon",
    model: "NIKKOR Z 24-70mm f/2.8 S",
    focalLength: "24-70mm",
    aperture: "f/2.8",
    mount: "Z",
    releaseYear: 2018,
  },
  {
    manufacturer: "Nikon",
    model: "NIKKOR Z 70-200mm f/2.8 VR S",
    focalLength: "70-200mm",
    aperture: "f/2.8",
    mount: "Z",
    releaseYear: 2020,
  },
  {
    manufacturer: "Nikon",
    model: "NIKKOR Z 50mm f/1.8 S",
    focalLength: "50mm",
    aperture: "f/1.8",
    mount: "Z",
    releaseYear: 2018,
  },
  {
    manufacturer: "Nikon",
    model: "NIKKOR Z 85mm f/1.8 S",
    focalLength: "85mm",
    aperture: "f/1.8",
    mount: "Z",
    releaseYear: 2019,
  },
  {
    manufacturer: "Nikon",
    model: "NIKKOR Z 14-30mm f/4 S",
    focalLength: "14-30mm",
    aperture: "f/4",
    mount: "Z",
    releaseYear: 2018,
  },

  // Fujifilm X
  {
    manufacturer: "Fujifilm",
    model: "XF 16-55mm F2.8 R LM WR",
    focalLength: "16-55mm",
    aperture: "f/2.8",
    mount: "X",
    releaseYear: 2015,
  },
  {
    manufacturer: "Fujifilm",
    model: "XF 50-140mm F2.8 R LM OIS WR",
    focalLength: "50-140mm",
    aperture: "f/2.8",
    mount: "X",
    releaseYear: 2015,
  },
  {
    manufacturer: "Fujifilm",
    model: "XF 35mm F1.4 R",
    focalLength: "35mm",
    aperture: "f/1.4",
    mount: "X",
    releaseYear: 2012,
  },
  {
    manufacturer: "Fujifilm",
    model: "XF 56mm F1.2 R",
    focalLength: "56mm",
    aperture: "f/1.2",
    mount: "X",
    releaseYear: 2014,
  },
  {
    manufacturer: "Fujifilm",
    model: "XF 10-24mm F4 R OIS WR",
    focalLength: "10-24mm",
    aperture: "f/4",
    mount: "X",
    releaseYear: 2017,
  },

  // Sigma (Sony E mount)
  {
    manufacturer: "Sigma",
    model: "24-70mm F2.8 DG DN Art",
    focalLength: "24-70mm",
    aperture: "f/2.8",
    mount: "E",
    releaseYear: 2019,
  },
  {
    manufacturer: "Sigma",
    model: "35mm F1.4 DG DN Art",
    focalLength: "35mm",
    aperture: "f/1.4",
    mount: "E",
    releaseYear: 2021,
  },
  {
    manufacturer: "Sigma",
    model: "85mm F1.4 DG DN Art",
    focalLength: "85mm",
    aperture: "f/1.4",
    mount: "E",
    releaseYear: 2020,
  },

  // Tamron (Sony E mount)
  {
    manufacturer: "Tamron",
    model: "28-75mm F/2.8 Di III VXD G2",
    focalLength: "28-75mm",
    aperture: "f/2.8",
    mount: "E",
    releaseYear: 2021,
  },
  {
    manufacturer: "Tamron",
    model: "70-180mm F/2.8 Di III VXD",
    focalLength: "70-180mm",
    aperture: "f/2.8",
    mount: "E",
    releaseYear: 2020,
  },
];
